# Generated by Django 5.2.7 on 2025-10-22 03:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('profession_id', models.AutoField(primary_key=True, serialize=False)),
                ('profession_title', models.CharField(blank=True, max_length=100, null=True)),
                ('profession_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profession',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=45, unique=True)),
                ('user_date_birth', models.DateField(blank=True, null=True)),
                ('user_img', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_date', models.DateTimeField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('feedback_rating', models.IntegerField(blank=True, null=True)),
                ('feedback_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('services_id', models.AutoField(primary_key=True, serialize=False)),
                ('services_title', models.CharField(blank=True, max_length=60, null=True)),
                ('services_description', models.TextField(blank=True, null=True)),
                ('services_price', models.IntegerField(blank=True, null=True)),
                ('services_img', models.TextField(blank=True, null=True)),
                ('services_status', models.CharField(blank=True, max_length=7, null=True)),
                ('services_profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dentistry.profession')),
            ],
            options={
                'db_table': 'services',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('workers_id', models.AutoField(primary_key=True, serialize=False)),
                ('workers_last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('workers_name', models.CharField(blank=True, max_length=45, null=True)),
                ('workers_description', models.CharField(blank=True, max_length=100, null=True)),
                ('workers_experience', models.IntegerField(blank=True, null=True)),
                ('workers_status', models.CharField(blank=True, max_length=10, null=True)),
                ('workers_profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dentistry.profession')),
            ],
            options={
                'db_table': 'workers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('medical_card_id', models.AutoField(primary_key=True, serialize=False)),
                ('medical_card_date', models.DateTimeField(blank=True, null=True)),
                ('medical_card_status', models.CharField(blank=True, max_length=12, null=True)),
                ('medical_card_diagnosis', models.CharField(blank=True, max_length=75, null=True)),
                ('medical_card_purpose', models.TextField(blank=True, null=True)),
                ('medical_card_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('medical_card_services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dentistry.services')),
                ('medical_card_workers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dentistry.workers')),
            ],
            options={
                'db_table': 'medical_card',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('appointment_status', models.CharField(blank=True, max_length=12, null=True)),
                ('appointment_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('appointment_services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dentistry.services')),
                ('appointment_workers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dentistry.workers')),
            ],
            options={
                'db_table': 'appointment',
                'managed': True,
            },
        ),
    ]
