# Generated by Django 5.2.7 on 2025-10-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='workers_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
