# Generated by Django 5.2.7 on 2025-11-01 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0002_workers_workers_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='workers_last_name',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='workers_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(default='пользователь', max_length=50),
        ),
        migrations.AddField(
            model_name='workers',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
