# Generated by Django 5.2.7 on 2025-11-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0003_remove_workers_workers_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='user_id',
            new_name='user',
        ),
    ]
