# Generated by Django 5.2.7 on 2025-11-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0004_rename_user_id_workers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('запланирован', 'запланирован'), ('отменен', 'отменен'), ('завершен', 'завершен')], default='запланирован', max_length=12),
        ),
    ]
